version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-presign"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l21bbeh9dn78"
s3_prefix = "s3-presign"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

